// Mocks generated by Mockito 5.4.0 from annotations
// in damodi_daily_mood_diary/test/models/api/quote_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:damodi_daily_mood_diary/models/api/quote_api.dart' as _i3;
import 'package:damodi_daily_mood_diary/models/quote_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuoteModel_0 extends _i1.SmartFake implements _i2.QuoteModel {
  _FakeQuoteModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuoteApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuoteApi extends _i1.Mock implements _i3.QuoteApi {
  MockQuoteApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.QuoteModel> getQuote() => (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [],
        ),
        returnValue: _i4.Future<_i2.QuoteModel>.value(_FakeQuoteModel_0(
          this,
          Invocation.method(
            #getQuote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.QuoteModel>);
}
